# Generated by Django 3.1.6 on 2021-02-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_user_magic_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="slug",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
