# Generated by Django 3.1.6 on 2021-02-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_link_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="link",
            name="data",
        ),
        migrations.AddField(
            model_name="link",
            name="counter",
            field=models.IntegerField(blank=True, default=True),
        ),
    ]
